### ISSUE TITLE
Our codes (and datasets) will be released soon!

### ISSUE THREAD

**Issue by zlccccc** [zlccccc/3DVL_Codebase#1]

**Comment by jianghaojun** [comment]
The paper of "3DJCG: A Unified Framework for Joint Dense Captioning and Visual Grounding on 3D Point Clouds" has not been published yet?

**Comment by zlccccc** [comment]
Our "3DJCG" has been accepted by cvpr2022. We will release the paper and open-source our codes after applying for the patent.

**Comment by ch3cook-fdu** [comment]
Could you provide the quantitative results on dense captioning and grounding here first?

**Comment by zlccccc** [comment]
Dense Captioning：
|             |   Data  | C@0.25 | B-4@0.25 | M@0.25 | R@0.25 | C@0.5 | B-4@0.5 | M@0.5 | R@0.5 |
|:-----------:|:-------:|:------:|:--------:|:------:|:------:|:-----:|:-------:|:-----:|:-----:|
|   Scan2Cap  | 3D Only |  53.73 |   34.25  |  26.14 |  54.95 | 35.20 |  22.36  | 21.44 | 43.57 |
|     3DJCG    | 3D Only |  60.86 |   39.67  |  27.45 |  59.02 | 47.68 |  31.53  | 24.28 | 51.08 |
|             |         |        |          |        |        |       |         |       |       |
| VoteNetRetr | 2D + 3D |  15.12 |   18.09  |  19.93 |  38.99 | 10.18 |  13.38  | 17.14 | 33.22 |
|   Scan2Cap  | 2D + 3D |  56.82 |   34.18  |  26.29 |  55.27 | 39.08 |  23.32  | 21.97 | 44.48 |
|     3DJCG    | 2D + 3D |  64.70 |   40.17  |  27.66 |  59.23 | 49.48 |  31.03  | 24.22 | 50.80 |

Visual Grounding：
|  Validation Set  |             |          |  Unique  |  Unique | Multiple | Multiple |  Overall | Overall |
|:----------------:|:-----------:|:--------:|:--------:|:-------:|:--------:|:--------:|:--------:|:-------:|
|      Methods     | Publication | Modality | Acc@0.25 | Acc@0.5 | Acc@0.25 |  Acc@0.5 | Acc@0.25 | Acc@0.5 |
|       SCRC       |    CVPR16   |    2D    |   24.03  |   9.22  |   17.77  |   5.97   |   18.70  |   6.45  |
|     One-Stage    |    ICCV19   |    2D    |   29.32  |  22.82  |   18.72  |   6.49   |   20.38  |   9.04  |
|                  |             |          |          |         |          |          |          |         |
|     ScanRefer    |   ECCV2020  |    3D    |   67.64  |  46.19  |   32.06  |   21.26  |   38.97  |  26.10  |
|       TGNN       |   AAAI2021  |    3D    |   68.61  |  56.80  |   29.84  |   23.18  |   37.37  |  29.70  |
|   InstanceRefer  |   ICCV2021  |    3D    |   77.45  |  66.83  |   31.27  |   24.77  |   40.23  |  32.93  |
|        SAT       |   ICCV2021  |    3D    |   73.21  |  50.83  |   37.64  |   25.16  |   44.54  |  30.14  |
| 3DVG-Transformer |   ICCV2021  |    3D    |   77.16  |  58.47  |   38.38  |   28.70  |   45.90  |  34.47  |
|    BEAUTY-DETR   |      -      |    3D    |     -    |    -    |     -    |     -    |   46.40  |    -    |
|      3D-SPS      |   CVPR2022  |    3D    |   81.63  |  64.77  |   39.48  |   29.61  |   47.65  |  36.43  |
|       3DJCG      |   CVPR2022  |    3D    |   78.75  |  61.30  |   40.13  |   30.08  |   47.62  |  36.14  |
|                  |             |          |          |         |          |          |          |         |
|     ScanRefer    |   ECCV2020  |  2D + 3D |   76.33  |  53.51  |   32.73  |   21.11  |   41.19  |  27.40  |
|       TGNN       |   AAAI2021  |  2D + 3D |   68.61  |  56.80  |   29.84  |   23.18  |   37.37  |  29.70  |
|   InstanceRefer  |   ICCV2021  |  2D + 3D |   75.72  |  64.66  |   29.41  |   22.99  |   38.40  |  31.08  |
| 3DVG-Transformer |   ICCV2021  |  2D + 3D |   81.93  |  60.64  |   39.30  |   28.42  |   47.57  |  34.67  |
|     MVT-3DVG     |   CVPR2022  |  2D + 3D |   77.67  |  66.45  |   31.92  |   25.26  |   40.80  |  33.26  |
|      3D-SPS      |   CVPR2022  |  2D + 3D |   84.12  |  66.72  |   40.32  |   29.82  |   48.82  |  36.98  |
|       3DJCG      |   CVPR2022  |  2D + 3D |   83.47  |  64.34  |   41.39  |   30.82  |   49.56  |  37.33  |

**Comment by ch3cook-fdu** [comment]
thanks! that helps a lot!
