### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by DafengChi** [zlccccc/3DVL_Codebase#10]
thanks for your great work,

where is the dataset (FE-3DGQA) ?

**Comment by zlccccc** [comment]
You can obtain the dataset from [this link](https://drive.google.com/drive/folders/1JR5AbuNHi_DFtIL-P1Wd_CF9QlpYG8cv?usp=share_link). For more detailed information, please refer to the [readme](https://github.com/zlccccc/3DVL_Codebase/blob/main/README_3DGQA.md).
