### ISSUE TITLE
question about loss function weights

### ISSUE THREAD

**Issue by ch3cook-fdu** [zlccccc/3DVL_Codebase#3]
In page 16468 of your paper. Is the weight of `boundary-reg` loss way too large?

$$
L_{detection} = 10L_{vote-reg} + L_{objn-cls} + L_{sem-cls} + 200L_{boundary-reg}
$$

**Comment by zlccccc** [comment]
We use huber_loss to represent boundary_reg loss. The weights are set empirically. Be free to change it by yourself.
https://github.com/zlccccc/3DJCG/blob/053ae910384d280cd4e4a4e473bfc003ab684d12/lib/loss_helper/loss_detection.py#L141
