### ISSUE TITLE
Other bugs

### ISSUE THREAD

**Issue by Zhang-Jing-Xuan** [zlccccc/3DVL_Codebase#5]
I try to visualize heatmap and run command:
```
python scripts/joint_scripts/heatmap_visualize.py --folder 2022-07-09_10-30-31_3DJCG --scene_id scene0011_00 --use_multiview --use_normal
```
Then, in the terminal, I meet an error:
![relation](https://user-images.githubusercontent.com/70561649/179653460-0acb2dcc-159b-490d-afda-288f210681ff.png)
In addition, I try to visualize caption, but I haven't got val.hdf5 file which is necessary to visualize caption (line 42 in scripts/joint_scripts/caption_visualize.py). Can you provide the link to this file?

**Comment by Zhang-Jing-Xuan** [comment]
I try to train the 3DJCG mode without multiview features:
```
python scripts/joint_scripts/train_3djcg.py --use_color --use_normal --use_topdown --num_graph_steps 0 --num_locals 20 --batch_size 10 --epoch 37 --gpu 1 --verbose 50 --val_step 1000 --lang_num_max 8 --coslr --lr 0.002 --num_ground_epoch 0 --tag 3djcg
```
```
python scripts/joint_scripts/train_3djcg.py  --use_normal --use_topdown --num_graph_steps 0 --num_locals 20 --batch_size 10 --epoch 37 --gpu 1 --verbose 50 --val_step 1000 --lang_num_max 8 --coslr --lr 0.002 --num_ground_epoch 0 --tag 3djcg
```
but there is an error in the terminal:
![error](https://user-images.githubusercontent.com/70561649/180234571-75330f9c-32e3-4bc9-81f5-32ea8b2a0bd4.png)

**Comment by zxc351200** [comment]
For data_dict['relation'] in heatmap_visualize.py，you can write these code in the relation module
![fcaa7484bac3bfcf0d405fab550bbd4](https://user-images.githubusercontent.com/38482166/185829947-b3f8ab45-1707-4886-9384-7056aab2c3cc.png)

For val.hdf5, please refer to Scan2Cap [README.md](https://github.com/daveredrum/Scan2Cap#3d-dense-captioning-with-ground-truth-bounding-boxes)

For train the 3DJCG mode without multiview features, you can change the code in the relation module as you need or you can change self.use_obj_embedding = True to self.use_obj_embedding = False int the relation module.
![850d7fd5b1de227c78e460443e12d38](https://user-images.githubusercontent.com/38482166/185830289-31f443a4-9b43-4082-9e16-aeda5c22ded4.jpg)

**Comment by Zhang-Jing-Xuan** [comment]
ok. Thank you for your reply.
