### ISSUE TITLE
The Detection Performance?

### ISSUE THREAD

**Issue by ch3cook-fdu** [zlccccc/3DVL_Codebase#6]
Can you share the detection performance (mAP@0.5, 0.25 and AR@0.5, 0.25) of your model? (without grounding, captioning head), or can you share the training command for training the detection branch only?

**Comment by ch3cook-fdu** [comment]
it would be great if you can share that of 3DVG too

**Comment by zlccccc** [comment]
I'm sorry I've been busy recently and haven't tested it. I tried the results of 3DJCG in the test set for dense captioning [here](https://kaldir.vc.in.tum.de/scanrefer_benchmark/benchmark_captioning.php?sortby=dmAP_0_5) and may be able to provide some references.
