### ISSUE TITLE
Unable to train with RGB inputs

### ISSUE THREAD

**Issue by ch3cook-fdu** [zlccccc/3DVL_Codebase#7]
File "/root/3DJCG/models/proposal_module/relation_module.py", line 111, in forward
    obj_embedding = self.obj_embedding[i](obj_feat)

input dimension error

**Comment by ch3cook-fdu** [comment]
The implementation in `models/proposal_module/relation_module.py`, line 95 - 97 is incorrect for RGB inputs, since PLC_COLOR is stored in `data_dict["point_clouds"][..., 3:6]`

```
# multiview/rgb feature embedding
if self.use_obj_embedding:
    obj_feat = data_dict["point_clouds"][..., 6:6 + 128].permute(0, 2, 1)
```

**Comment by zlccccc** [comment]
Fixed now.
