### ISSUE TITLE
Thesis Figure Consultation

### ISSUE THREAD

**Issue by gaohan-cmd** [zlccccc/3DVL_Codebase#9]
Hello, after reading your paper, I was really impressed by not only the innovative research but also the beautiful and intuitive way the graphs were presented. I wanted to ask you, how did you create such exquisite charts? Which specific libraries or tools did you use? For example, the following few.
![Toward Explainable 3D Grounded Visual Question Answering_ A New Benchmark and Strong Baseline _ IEEE Journals   Magazine _ IEEE Xplore](https://github.com/zlccccc/3DVL_Codebase/assets/63499259/1b9593c2-1bc2-480b-ae6d-570c60b4455a)
![Toward Explainable 3D Grounded Visual Question Answering_ A New Benchmark and Strong Baseline _ IEEE Journals   Magazine _ IEEE Xplore](https://github.com/zlccccc/3DVL_Codebase/assets/63499259/ccf9c798-4c2e-42f9-8917-f59ca3ead443)
![Toward Explainable 3D Grounded Visual Question Answering_ A New Benchmark and Strong Baseline _ IEEE Journals   Magazine _ IEEE Xplore](https://github.com/zlccccc/3DVL_Codebase/assets/63499259/e5748df3-a74b-4c6b-82af-dcf18cf3380e)

**Comment by zlccccc** [comment]
We created charts using matplotlib.pyplot and PowerPoint. [Here](https://www.geeksforgeeks.org/plot-a-pie-chart-in-python-using-matplotlib/) is an example. But it's been too long and the script can no longer be found. Sorry.
